version: "3.7"
services:
  postgres:
    environment:
    - TZ=America/Chicago
    image: postgres:14.4
    volumes:
    - db-data:/var/lib/postgresql/data
    restart: always
    # network_mode: host
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
  nzyme:
    environment:
    - TZ=America/Chicago
    build: 
      context: nzyme
      args:
        - GRAYLOG_SERVER=${GRAYLOG_SERVER}
        - GRAYLOG_GELF_TCP_PORT=${GRAYLOG_GELF_TCP_PORT}
        - WIFI_INTERFACE=${WIFI_INTERFACE}
        - WIFI_CHANNELS=${WIFI_CHANNELS}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        - NZYME_PASSWORD=${NZYME_PASSWORD}
    depends_on:
      - postgres
    # network_mode: host
    privileged: true # for allowing channel hopping / setting monitor mode from nzyme
    ports:
     - "22900:22900"
volumes:
  db-data: