version: "3.7"
services:
  nzyme:
    build: 
      context: nzyme
      args:
        - GRAYLOG_SERVER=${GRAYLOG_SERVER}
        - GRAYLOG_GELF_TCP_PORT=${GRAYLOG_GELF_TCP_PORT}
        - WIFI_INTERFACE=${WIFI_INTERFACE}
        - WIFI_CHANNELS=${WIFI_CHANNELS}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        - NZYME_PASSWORD=${NZYME_PASSWORD}
    depends_on:
      - postgres
    network_mode: host
    privileged: true # for allowing channel hopping / setting monitor mode from nzyme
    ports:
      - "22900:22900"

  postgres:
    image: postgres:14.4
    restart: always
    network_mode: host
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}